enum MicaSymbols {
    enum Workspace {
        static let overview = "rectangle.3.group"
        static let routing = "arrow.triangle.branch"
        static let traffic = "chart.line.uptrend.xyaxis"
        static let diagnostics = "checklist"
    }

    enum Controller {
        static let autoDetect = "desktopcomputer"
        static let mihomo = "desktopcomputer"
        static let nikki = "desktopcomputer"
        static let openClash = "network"
        static let surge = "bolt.horizontal.circle"
        static let singBox = "shippingbox"
        static let stashCmfa = "square.stack.3d.up"
        static let unknown = "desktopcomputer"
        static let unsupported = "exclamationmark.triangle"
    }

    enum Command {
        static let add = "plus.circle"
        static let test = "checkmark.circle"
        static let refresh = "arrow.clockwise.circle"
        static let close = "xmark.circle"
        static let copy = "doc.on.doc"
        static let edit = "pencil.circle"
        static let delete = "trash.circle"
        static let search = "magnifyingglass"
        static let clear = "trash.circle"
        static let unpin = "pin.slash"
        static let ready = "checkmark.circle"
        static let warning = "exclamationmark.triangle"
        static let working = "hourglass"
        static let run = "play.circle"
        static let save = "checkmark.circle"
        static let sortAscending = "arrow.up"
        static let sortDescending = "arrow.down"
    }

    enum Operation {
        static let liveTelemetry = "dot.radiowaves.left.and.right"
        static let refreshData = "arrow.triangle.2.circlepath.circle"
        static let pause = "pause.circle"
        static let resume = "play.circle"
    }

    enum Data {
        static let identity = "tag"
        static let rules = "checklist"
        static let providers = "cube.box"
        static let logs = "doc.text.magnifyingglass"
        static let connection = "cable.connector"
        static let upload = "arrow.up.circle"
        static let download = "arrow.down.circle"
        static let health = "waveform.path.ecg"
        static let config = "slider.horizontal.3"
        static let version = "number.circle"
        static let policy = "list.bullet.rectangle"
        static let policyGroup = "rectangle.3.group"
        static let activeRequests = "bolt.horizontal.circle"
        static let recentRequests = "clock.badge"
        static let dnsCache = "globe"
        static let lan = "network"
        static let ipv6 = "6.circle"
        static let tunnel = "point.topleft.down.curvedto.point.bottomright.up"
        static let port = "cable.connector"
        static let http = "globe"
        static let socks = "arrow.left.and.right"
        static let redirect = "arrow.turn.down.right"
        static let switchControl = "switch.2"
        static let liveSamples = "waveform.path.ecg"
        static let liveEvents = "list.bullet.rectangle"
        static let table = "tablecells"
        static let report = "doc.text.magnifyingglass"
        static let routeScope = "scope"
        static let latency = "gauge"
        static let providerItems = "square.stack.3d.up"
        static let updatedAt = "clock.arrow.circlepath"
        static let nextStep = "arrow.turn.down.right"
        static let language = "globe"
        static let textSize = "textformat.size"
        static let appearance = "circle.lefthalf.filled"
        static let keychain = "key"
        static let hidden = "eye.slash"
        static let visible = "eye"
        static let insight = "chart.pie.fill"
        static let routeHealth = "speedometer"
        static let trafficSplit = "arrow.up.arrow.down.circle"
        static let topFlows = "list.number"
        static let emptyFolder = "folder"
        static let memory = "memorychip"
        static let processor = "cpu"
    }
}
